### PR TITLE
Click Fix for Range Slider Rail

### PR DESCRIPTION
**Pull request by FreshCourageTake**
.range-slider-rail was missing from event listener array. This caused a bug where clicking on the slider rail would not update the range value as expected. Simply adding this class to the array of event listeners fixed the issue.

### CODE REVIEW

**Review by mykeels — APPROVED** [review]
Woah, thanks!

**Comment by FreshCourageTake** [comment]
No problem! Awesome work!

**Comment by FreshCourageTake** [comment]
Let me know when you publish the next npm version with the fix :)

**Comment by mykeels** [comment]
Done! @andrewsgarver

**Pull request merged**
